<?php
/**
 * 24/01/26 Generated by component-generator.com
 * 26/01/26 CB delete unwanted buttons/actions
 * 27/01/26 CB add Cancel button
 * 21/09/26 CB Restrict update of areas to superUsers
 */

namespace Ramblers\Component\Ra_tools\Administrator\View\Clusters;
// No direct access
defined('_JEXEC') or die;

use \Joomla\CMS\MVC\View\HtmlView as BaseHtmlView;
use Joomla\CMS\Helper\ContentHelper;
use \Joomla\CMS\Toolbar\Toolbar;
use \Joomla\CMS\Toolbar\ToolbarHelper;
use \Joomla\CMS\Language\Text;
use \Joomla\Component\Content\Administrator\Extension\ContentComponent;
use \Joomla\CMS\Form\Form;
use \Joomla\CMS\HTML\Helpers\Sidebar;
use Ramblers\Component\Ra_tools\Site\Helpers\ToolsHelper;
/**
 * View class for a list of Clusters.
 *
 * @since  3.4.8
 */
class HtmlView extends BaseHtmlView
{
	protected $items;

	protected $pagination;

	protected $state;
	protected $toolsHelper;

	/**
	 * Display the view
	 *
	 * @param   string  $tpl  Template name
	 *
	 * @return void
	 *
	 * @throws Exception
	 */
	public function display($tpl = null)
	{
		$this->state = $this->get('State');
		$this->items = $this->get('Items');
		$this->pagination = $this->get('Pagination');
		$this->filterForm = $this->get('FilterForm');
		$this->activeFilters = $this->get('ActiveFilters');
		$this->toolsHelper = new ToolsHelper;

		// Check for errors.
		if (count($errors = $this->get('Errors')))
		{
			throw new \Exception(implode("\n", $errors));
		}

		$this->addToolbar();

		$this->sidebar = Sidebar::render();
		parent::display($tpl);
	}

	/**
	 * Add the page title and toolbar.
	 *
	 * @return  void
	 *
	 * @since   3.4.8
	 */
	protected function addToolbar()
	{
		$state = $this->get('State');
		$canDo = ContentHelper::getActions('com_ra_tools');

		ToolbarHelper::title(Text::_('Clusters'), "generic");

		$toolbar = Toolbar::getInstance('toolbar');

		// Check if the form exists before showing the add/edit buttons
		$formPath = JPATH_COMPONENT_ADMINISTRATOR . '/src/View/Clusters';

		if (file_exists($formPath))
		{
			if ($canDo->get('core.create'))
			{
				$toolbar->addNew('cluster.add');
			}
		}
		if ($this->toolsHelper->isSuperuser()) {
            $toolbar->standardButton('nrecords')
                    ->icon('fa fa-info-circle')
                    ->text(number_format($this->pagination->total) . ' Records')
                    ->task('')
                    ->onclick('return false')
                    ->listCheck(false);
		}
					$toolbar->standardButton('refresh')
                    ->text('Refresh Areas')
                    ->task('clusters.updateClusters')
                    ->onclick('return false')
                    ->listCheck(false);
            ToolbarHelper::cancel('apisites.cancel', 'Return to Dashboard');		

		// Set sidebar action
		Sidebar::setAction('index.php?option=com_ra_tools&view=clusters');
	}
	
	/**
	 * Method to order fields 
	 *
	 * @return void 
	 */
	protected function getSortFields()
	{
		return array(
			'a.`id`' => Text::_('JGRID_HEADING_ID'),
			'a.`name`' => Text::_('COM_RA_TOOLS_CLUSTERS_NAME'),
			'a.`website`' => Text::_('COM_RA_TOOLS_CLUSTERS_WEBSITE'),
			'a.`code`' => Text::_('COM_RA_TOOLS_CLUSTERS_CODE'),
		);
	}

	/**
	 * Check if state is set
	 *
	 * @param   mixed  $state  State
	 *
	 * @return bool
	 */
	public function getState($state)
	{
		return isset($this->state->{$state}) ? $this->state->{$state} : false;
	}
}
