<?php
/**
 * 24/01/26 Generated by component-generator.com
 * 26/01/26 CB add contact
 * 21/09/26 CB remove check-box column
 */

// No direct access
defined('_JEXEC') or die;


use \Joomla\CMS\HTML\HTMLHelper;
use \Joomla\CMS\Factory;
use \Joomla\CMS\Uri\Uri;
use \Joomla\CMS\Router\Route;
use \Joomla\CMS\Layout\LayoutHelper;
use \Joomla\CMS\Language\Text;
use Joomla\CMS\Session\Session;

HTMLHelper::_('bootstrap.tooltip');
HTMLHelper::_('behavior.multiselect');

// Import CSS
$wa =  $this->document->getWebAssetManager();
$wa->useStyle('com_ra_tools.admin')
    ->useScript('com_ra_tools.admin');

$user      = Factory::getApplication()->getIdentity();
$userId    = $user->get('id');
$listOrder = $this->state->get('list.ordering');
$listDirn  = $this->state->get('list.direction');

?>

<form action="<?php echo Route::_('index.php?option=com_ra_tools&view=clusters'); ?>" method="post"
	  name="adminForm" id="adminForm">
	<div class="row">
		<div class="col-md-12">
			<div id="j-main-container" class="j-main-container">
			<?php echo LayoutHelper::render('joomla.searchtools.default', array('view' => $this)); ?>

				<div class="clearfix"></div>
				<table class="table table-striped" id="clusterList">
					<thead>
					<tr>			
						<th class='left'>
							<?php echo HTMLHelper::_('searchtools.sort',  'Code', 'a.code', $listDirn, $listOrder); ?>
						</th>
						<th class='left'>
							<?php echo HTMLHelper::_('searchtools.sort',  'Name', 'a.name', $listDirn, $listOrder); ?>
						</th>
						<th class='left'>
							<?php echo HTMLHelper::_('searchtools.sort',  'Website', 'a.website', $listDirn, $listOrder); ?>
						</th>
						<th class='left'>
							<?php echo HTMLHelper::_('searchtools.sort',  'Contact', 'c.name', $listDirn, $listOrder); ?>
						</th>						
					<th scope="col" class="w-3 d-none d-lg-table-cell" >

						<?php echo HTMLHelper::_('searchtools.sort',  'JGRID_HEADING_ID', 'a.id', $listDirn, $listOrder); ?>					</th>
					</tr>
					</thead>
					<tfoot>
					<tr>
						<td colspan="<?php echo isset($this->items[0]) ? count(get_object_vars($this->items[0])) : 10; ?>">
							<?php echo $this->pagination->getListFooter(); ?>
						</td>
					</tr>
					</tfoot>
					<tbody> 
					<?php foreach ($this->items as $i => $item) :

						$canCreate  = $user->authorise('core.create', 'com_ra_tools');
						$canEdit    = $user->authorise('core.edit', 'com_ra_tools');
						$canCheckin = $user->authorise('core.manage', 'com_ra_tools');
						$canChange  = $user->authorise('core.edit.state', 'com_ra_tools');
						?>
						<tr class="row<?php echo $i % 2; ?>" data-draggable-group='1' data-transition>
			
							<td>
								<?php if ($canEdit) : ?>
									<a href="<?php echo Route::_('index.php?option=com_ra_tools&task=cluster.edit&id='.(int) $item->id); ?>">
									<?php echo $this->escape($item->code); ?>
									</a>
								<?php else : ?>
												<?php echo $this->escape($item->code); ?>
								<?php endif; ?>
							</td>
							<td>
								<?php echo $item->name; ?>
							</td>
							<td>
								<?php echo $item->website; ?>
							</td>
							<td>
								<?php echo $item->contact; ?>
							</td>						
							<td class="d-none d-lg-table-cell">
							<?php echo $item->id; ?>

							</td>


						</tr>
					<?php endforeach; ?>
					</tbody>
				</table>

				<input type="hidden" name="task" value=""/>
				<input type="hidden" name="boxchecked" value="0"/>
				<input type="hidden" name="list[fullorder]" value="<?php echo $listOrder; ?> <?php echo $listDirn; ?>"/>
				<?php echo HTMLHelper::_('form.token'); ?>
			</div>
		</div>
	</div>
</form>
